### PR TITLE
Some cleanup of formatters

### PR DESCRIPTION
**Pull request by coreyhaines**
This removes a deprecation with the specific color methods (yellow, green, red), upgrading to the newer #success_color, etc.
Also cleaned up the adventure time randomization to use Array#sample, rather than randomly choosing up to size.
Also creates a Base formatter in here to handle the integration with RSpec. The individual subclass formatters just override simple display methods to return the character for each type

### CODE REVIEW

**Comment by cupakromer** [comment]
:smile: Thanks! This gem is over-due for some maintenance, so this is a good kick start (_/me :facepunch:_). A bit :grimacing: in my `rand_emoji`. After I learned of `sample` I didn't update the gem :unamused:. So big thanks on that!

I agree with everything, but the naming of [`Base`](https://github.com/coreyhaines/emoji-rspec/blob/4b889bb38dce944bae0c2fbc5efc6c03d8edc6b2/lib/emoji/rspec/formatters/base.rb#L6). It's something that isn't overly descriptive and overused (thanks Rails). Also there is already a [`RSpec::Core::Formatters::BaseFormatter`](https://github.com/rspec/rspec-core/blob/v2.13.0/lib/rspec/core/formatters/base_formatter.rb#L13).

I'm thinking of changing it to `EmojiFormatter`. (Yes, it'll be a bit redundant `Emoji::RSpec::Formatters::EmojiFormatter`). **Thoughts or other suggestions?**

I do like the extraction of the base class. My initial thought was just duck type it so no need for the base class. However, I want to make this more dynamic in how it hooks into RSpec core (core patch in the works). Which means using the [`Module::included`](http://ruby-doc.org/core-2.0/Module.html#method-i-included) or [`Class::inherited`](http://ruby-doc.org/core-2.0/Class.html#method-i-inherited) tricks, so this fits perfectly.

**Comment by coreyhaines** [comment]
On Mar 1, 2013 7:21 PM, "Aaron Kromer" notifications@github.com wrote:

> I agree with everything, but the naming of Base. It's something that
> isn't overly descriptive and overused (thanks Rails). Also there is already
> a RSpec::Core::Formatters::BaseFormatter.
> 
> I'm thinking of changing it to EmojiFormatter. (Yes, it'll be a bit
> redundant Emoji::RSpec::Formatters::EmojiFormatter). Thoughts or other
> suggestions?

Yeah, Base is a punt. Was thinking about it and realized what it is: it is
the especially integration. Let's move it upwards in the namespace
hierarchy to maybe Emoji::RSpec::Integration or something like that. The
point of the class is to manage the link between what rspec wants us to
provide (#example_passed) and our concern (what to display)

Thoughts on that?

**Comment by coreyhaines** [comment]
I'm going to be booked up for the next few days (through Wednesday), but I can make a pass at this on Thursday.

**Comment by cupakromer** [comment]
Sure no problem. I took a weekend off from the interwebs and am catching up with work now. Will look at this later tonight / tomorrow.

**Comment by stevenhaddox** [comment]
Any chance this is getting merged / released soon? Just heard about it and am love with the idea of emoji as an alternative to the nyan cat formatter I've been using as of late... The deprecation output makes this unusable currently (and unfortunately I can't pull from a git repository when developing a gem).

**Comment by cupakromer** [comment]
@stevenhaddox Yes! Was busy earlier this week, but plan on merging and pushing a new version before the weekend.

**Comment by cupakromer** [comment]
@coreyhaines So looking over things, I'm in agreement for using `Emoji::RSpec::Integration`

**Comment by coreyhaines** [comment]
Yeah. Let's merge this in and refactor it on a separate branch. I have some ideas on how to take it out of the inheritance hierarchy and into a more delegation-based model. This will allow us to take the step towards my ultimate goal, which is supporting minitest, as well.

**Comment by cupakromer** [comment]
:+1:

**Comment by cupakromer** [comment]
Created a new branch for the delegation: https://github.com/cupakromer/emoji-rspec/tree/delegation-based

**Comment by cupakromer** [comment]
@coreyhaines What sort of delegation were you thinking of? `SimpleDelegator`? Mix-in?

**Pull request merged**
