### PR TITLE
Support for Rspec 3, dumping older versions.

### PR DESCRIPTION
**Pull request by carhartl**
Alternative pull request for RSpec 3 support, and since requiring RSpec 3 bumping mayor version...

### CODE REVIEW

**Comment by carhartl** [comment]
Just realized that this (unintentionally, but missing the bigger picture), may counteract the work being done by @coreyhaines towards minitest support. Feel free to close it. I'm also going to think about how to add minitest support on top of that.

**Comment by cupakromer** [comment]
I think this is a good start. I don't want to close it just yet. Based on the way you did the commits we can probably keep going forward. Here's my suggestions:
- Remove b16d177 from history (this may require removing 6b30445 as well)
- Leave the runtime dependency as `>= 2.10`; I think we can make all of this work and easily support both RSpec 2 and 3
- Bump the default RSpec **development** version for the gem to 3.0; update `.rspec` and `spec/spec_helper.rb` with any missing defaults which are now part of RSpec 3
- Run [`transpec`](https://github.com/yujinakayama/transpec) against all the specs and merge with 7d5f994

That should get the base of the gem current. Now to talk about more about implementation. As per your previous comment, the original goal was for broader formatter support. The lib just hasn't gotten to that point yet. Given the new nature of the RSpec 3 formatters we can keep most of the logic in place. My suggestions are:
- Pull the [existing notification hooks](https://github.com/cupakromer/emoji-rspec/blob/99ff00aa20987604a7dfef04a178ca33dfb0e19c/lib/emoji_test_love/rspec/rspec_integration.rb#L31-L44) into an RSpec 2 specific module
- Create a new RSpec 3 specific module which implements those methods and the now required `start_dump` (see the [`ProgressFormatter`](https://github.com/rspec/rspec-core/blob/2f03e35d5fd553bee31bf24199903368b1d2f8af/lib/rspec/core/formatters/progress_formatter.rb) for a sample)
- I generally dislike checking versions when having to conditionally choose a code path to take, instead I prefer to rely on Ruby's [`respond_to?`](http://ruby-doc.org/core-2.1.2/Object.html#method-i-respond_to-3F) as my feature toggle. Here we can check for the registration method: `RSpec::Core::Formatters.respond_to?(:register)`. If it exists, include the RSpec 3 module into the `RSpecIntegration` class, otherwise, include the RSpec 2 module

The last thing then would probably be updating the actual RSpec monkey patch. That will be a bit trickier and it's fine to leave it out of this PR. I'll need to ponder it for another day or so. Also, don't bump the gem version just yet. I have a few other things I'd like to get in first.

**Comment by cupakromer** [comment]
@carhartl are you going to have any more time coming up to work on this? if not I can help finish it up.

**Comment by carhartl** [comment]
I planned putting more work into this, though I can't tell when exactly. It might take a bit...

**Comment by cupakromer** [comment]
@carhartl are you going to have time to work on this soon? I could pull it into a branch and finish it up if you don't have the time.

**Comment by carhartl** [comment]
I'm pretty sure no sooner than next week.

**Comment by sbansal** [comment]
Any idea when this PR is going to be merged?

**Comment by davetoxa** [comment]
@cupakromer why you are not merging this?

**Comment by cupakromer** [comment]
@davetoxa the PR is not ready to be merged. Several issues have been raised which still need to be addressed. Hopefully, things will be finished soon.

**Pull request closed without merging**
